services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped

    ports:
      - "${DOCKER_MINIO_PORT:-9000}:9000"
      - "${DOCKER_MINIO_CONSOLE_PORT:-9001}:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio_data:/data
    networks:
      - app

    command: server /data --console-address ":9001"

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - "${DOCKER_RABBITMQ_PORT:-5672}:5672"
      - "${DOCKER_RABBITMQ_CONSOLE_PORT:-15672}:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./assets/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./assets/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - app

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  image-scheduler:
    build:
      context: scheduler
      dockerfile: Dockerfile
    container_name: scheduler-service
    init: true
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

    env_file:
      - .env
    networks:
      - app

  image-fetcher:
    build:
      context: fetcher
      dockerfile: Dockerfile
    container_name: fetcher-service
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy

    env_file:
      - .env
    networks:
      - app

  image-thumbnail-processor:
    build:
      context: thumbnail_processor
      dockerfile: Dockerfile
    container_name: thumbnail-processor-service
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy

    env_file:
      - .env
    networks:
      - app

  image-metadata-processor:
    build:
      context: metadata_processor
      dockerfile: Dockerfile
    container_name: metadata-processor-service
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_started
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

    env_file:
      - .env
    networks:
      - app

  image-notifier:
    build:
      context: notifier
      dockerfile: Dockerfile
    container_name: notifier-service
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy

    env_file:
      - .env
    networks:
      - app

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started

    ports:
      - "${DOCKER_BACKEND_PORT:-8080}:8080"

    env_file:
      - .env
    networks:
      - app

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

    ports:
      - "${DOCKER_FRONTEND_PORT:-80}:80"

    networks:
      - app

  loki:
    image: grafana/loki:3.7.0
    command:
      - -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./assets/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${DOCKER_GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ROOT_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ROOT_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./assets/grafana/loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml:ro
    depends_on:
      - loki
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - /etc/alloy/config.alloy
    volumes:
      - ./assets/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - observability
      - app

volumes:
  minio_data:
  postgres_data:
  rabbitmq_data:
  loki_data:
  grafana_data:

networks:
  app:
  observability:
