import typing


class Storage(typing.Protocol):
    async def upload_image(self, bucket: str, id: str, contents: bytes) -> None: ...
    async def download_image(self, bucket: str, id: str) -> bytes: ...
